name: Deploy WhatsApp Bot

on:  
  push:  
    branches: [ main ]  # Runs when you push to the `main` branch
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Bot
        run: node index.js
        env:
          YOUR_NUMBER: ${{ secrets.YOUR_NUMBER }}  # Inject Secret as ENV variable
